/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 brain.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/brain.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Olfactory_Bulb_R.geometry} material={materials.Olfactory_bulb} position={[2.74, 8.48, 1.12]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Olfactory_Bulb_L.geometry} material={materials.Olfactory_bulb} position={[-0.02, 6.74, -3.13]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Cerebrum_R.geometry} material={materials.Cerebrum_R} position={[2.74, 8.48, 1.12]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Cerebrum_L.geometry} material={materials.Cerebrum_L} position={[-2.79, 8.56, 1.11]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Pons.geometry} material={materials.Brain_base} position={[-0.02, -161.81, 0.84]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={2.54} />
      <mesh geometry={nodes.Cerebral_Peduncle.geometry} material={materials.Brain_base} position={[-0.02, 2.88, 1.91]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Pituitary_Gland.geometry} material={materials.Brain_base} position={[-0.02, 6.81, 0.98]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Fourth_Ventricle_Wall.geometry} material={materials.Brain_base} position={[-0.02, 6.81, 0.98]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Tuber_Cinereum.geometry} material={materials.Brain_base} position={[-0.02, 6.81, 0.98]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Mammillary_Body_R.geometry} material={materials.Brain_base} position={[-0.02, 6.81, 0.98]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Optic_Chiasm.geometry} material={materials.Brain_base} position={[-0.02, 6.81, 0.98]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Inferior_Colliculus_R.geometry} material={materials.Brain_base} position={[-0.02, 6.81, 0.98]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Superior_Colliculus_R.geometry} material={materials.Brain_base} position={[-0.02, 6.81, 0.98]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Pineal_Gland.geometry} material={materials.Brain_base} position={[-0.02, 6.81, 0.98]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Medulla_Oblongata.geometry} material={materials.Brain_base} position={[-0.02, 2.88, 1.91]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Optic_Tract_R.geometry} material={materials.Brain_base} position={[-0.02, 6.81, 0.98]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Mammillary_Body_L.geometry} material={materials.Brain_base} position={[-0.02, 6.81, 0.98]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Optic_Tract_L.geometry} material={materials.Brain_base} position={[-0.02, 6.81, 0.98]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Superior_Colliculus_L.geometry} material={materials.Brain_base} position={[-0.02, 6.81, 0.98]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Inferior_Colliculus_L.geometry} material={materials.Brain_base} position={[-0.02, 6.81, 0.98]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Fornix.geometry} material={materials.Brain_internal_alt} position={[-0.02, 7.28, -0.05]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.3} />
      <mesh geometry={nodes.Indusium_griseum.geometry} material={materials.Brain_internal_alt} position={[-0.02, 7.28, -0.05]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.3} />
      <mesh geometry={nodes.Medial_olfactory_striae.geometry} material={materials.Brain_internal_alt} position={[-0.02, 7.28, -0.05]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.3} />
      <mesh geometry={nodes.Olfactory_bulb.geometry} material={materials.Brain_internal_alt} position={[-0.02, 7.28, -0.05]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.3} />
      <mesh geometry={nodes.Cingulate_gyrus.geometry} material={materials.Brain_internal_alt} position={[-0.02, 7.28, -0.05]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.3} />
      <mesh geometry={nodes.Commissura_fornicics.geometry} material={materials.Brain_internal_alt} position={[-0.02, 7.28, -0.05]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.3} />
      <mesh geometry={nodes.Corpus_callosum.geometry} material={materials.Brain_internal_alt} position={[-0.02, 7.28, -0.05]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.3} />
      <mesh geometry={nodes.Dentate_gyrus.geometry} material={materials.Brain_internal_alt} position={[-0.02, 7.28, -0.05]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.3} />
      <mesh geometry={nodes.Hyppocampus.geometry} material={materials.Brain_internal_alt} position={[-0.02, 7.28, -0.05]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.3} />
      <mesh geometry={nodes.Amygdala.geometry} material={materials.Brain_internal_alt} position={[-0.02, 7.28, -0.05]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.3} />
      <mesh geometry={nodes.Hypothalamus.geometry} material={materials.Brain_internal_alt} position={[-0.02, 7.28, -0.05]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.3} />
      <mesh geometry={nodes.Putamen.geometry} material={materials.Brain_internal_alt} position={[-0.02, 7.28, -0.05]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.3} />
      <mesh geometry={nodes.Septal_nucleus.geometry} material={materials.Brain_internal_alt} position={[-0.02, 7.28, -0.05]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.3} />
      <mesh geometry={nodes.Thalamus.geometry} material={materials.Brain_internal_alt} position={[-0.02, 7.28, -0.05]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.3} />
      <mesh geometry={nodes.Arteries.geometry} material={materials.Arteries} position={[-0.02, -161.81, 0.84]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Veins.geometry} material={materials.Veins} position={[-0.02, -161.81, 0.84]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Cerebellum.geometry} material={materials.Cerebellum} position={[-0.04, 0.22, 0.83]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={2.2} />
    </group>
  )
}

useGLTF.preload('/brain.gltf')
